RDKCOM-4441: REFPLTB-2793: RdkLedManager compilation issue in kirkstone
Reason for change: In recent kirkstone build, faced below issue
rdkb/components/opensource/ccsp/RdkLedManager/source/led_manager_dbus_utils.c:327:18: error: passing argument 4 of 'CCSP_Message_Bus_Init' from incompatible pointer type [-Werror=incompatible-pointer-types]
|   327 |                  AllocateMemory_Callback,           /* mallocfc, use default */
|       |                  ^~~~~~~~~~~~~~~~~~~~~~~
|       |                  |
|       |                  void * (*)(unsigned int)
Test Procedure: 1. Verified that it is not affecting dunfell build.
                2. bitbake rdk-ledmanager
Risks: None
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>
Priority: P1

Change-Id: Iffb4d10b99d257ad98b35a938147422f9739bc35
(cherry picked from commit c72935fba25cfffeeada464fdf1c3cf480ac2275)